HOST = "https://api.graphindexer.co/"
API_GET_CLOSE_ACTIONS = HOST + "/api/closeActions"
API_GET_OPEN_ACTIONS = HOST + "/api/openActions"
API_UPDATE_EXE_STATUS = HOST + "/api/updateExeStatus"
API_UPDATE_TIME = HOST + "/api/updateTime"

CLOSE_ACTION=1
OPEN_ACTION=2
OFFCHAIN_ACTION=3
RE_ALLOCATION_ACTION=4

STATUS_QUEUE="Queue"
STATUS_APPROVE="Approved"

GRAPHMAN_REASSIGN = "reassign"
GRAPHMAN_UNASSIGN = "unassign"
GRAPHMAN_REMOVE = "remove"
GRAPHMAN_REWIND = "rewind"

#Error

TOKEN_ERROR = "TOKEN ERROR"
ERROR = "ERROR"
SUCCESS = "OK"

VERSION = "1.0.1"